version: 0.2
batch:
  fast-fail: false
  build-graph:
    - identifier: build1
      buildspec: ./buildspec1.yml
    - identifier: build2
      buildspec: ./buildspec2.yml
      depend-on:
        - build1

phases:
  build:
    commands:
    - echo "testing bactch"

